services:
  vault:
    container_name: vault
    image: vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: "http://0.0.0.0:8200"
    volumes:
      - vault:/data/vault
    ports:
      - "8200:8200"
    networks:
      - vault
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: samasama
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
  vault:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  vault: