server:
  port: 8082
spring:
  application:
    name: notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail.email}
    password: ${gmail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    vault:
      kv:
        enabled: true
      authentication: TOKEN
      token: root
      scheme: http
      host: 127.0.0.1
      port: 8200
  config:
    import: vault://
  rabbitmq:
    addresses: localhost:5672
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.datasource.database}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
  profiles:
    active: default
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

gmail:
  email: ${gmail.email}
  password: ${gmail.password}